# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 03:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='城市名称')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '城市信息',
                'verbose_name_plural': '城市信息',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='机构名称')),
                ('describe', models.TextField(verbose_name='机构简介')),
                ('image', models.ImageField(upload_to='org/%Y-%d', verbose_name='机构封面')),
                ('address', models.CharField(max_length=200, verbose_name='机构地址')),
                ('click_nums', models.IntegerField(verbose_name='点击数')),
                ('collect_nums', models.IntegerField(verbose_name='收藏数')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.City', verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '组织机构',
                'verbose_name_plural': '组织机构',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='教师姓名')),
                ('work_year', models.IntegerField(max_length=10, verbose_name='工龄')),
                ('work_company', models.CharField(max_length=20, verbose_name='工作单位')),
                ('position', models.CharField(max_length=20, verbose_name='职位')),
                ('feature', models.CharField(max_length=100, verbose_name='教学特点')),
                ('click_nums', models.IntegerField(verbose_name='点击数')),
                ('collect_nums', models.IntegerField(verbose_name='收藏数')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
            },
        ),
    ]
